import { Container } from '../types/terminal';

export const INITIAL_CONTAINERS: Omit<Container, 'id'>[] = [
  {
    containerNumber: 'MSKU8291034',
    isoType: '40HC',
    teu: 2,
    status: 'YARD_STACKING',
    category: 'EKSPOR',
    grossWeightKg: 28450,
    tareWeightKg: 3900,
    payloadKg: 24550,
    vgmVerified: true,
    sealNumber: 'MSK-992182',
    shippingLine: 'Maersk Line',
    vesselName: 'MV MAERSK MC-KINNEY MOLLER',
    voyageNumber: '2405W',
    yardLocation: { block: 'A', bay: '04', row: '02', tier: '03' },
    isReefer: false,
    temperatureCelsius: null,
    dangerClass: 'NON_DG',
    shipper: 'PT INDO FURNITURE GLOBAL',
    consignee: 'NORDIC LIVING APS (DENMARK)',
    gateInTime: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'B 9821 UIO',
    driverName: 'Bambang Sugianto',
    notes: 'Muatan mebel jati ekspor Eropa, siap muat ke palka kapal.',
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    containerNumber: 'MRTU4519280',
    isoType: '20GP',
    teu: 1,
    status: 'YARD_STACKING',
    category: 'DOMESTIK',
    grossWeightKg: 18200,
    tareWeightKg: 2200,
    payloadKg: 16000,
    vgmVerified: true,
    sealNumber: 'MRT-771239',
    shippingLine: 'Meratus Line',
    vesselName: 'KM MERATUS SAMARINDA',
    voyageNumber: 'V.12B',
    yardLocation: { block: 'B', bay: '02', row: '01', tier: '02' },
    isReefer: false,
    temperatureCelsius: null,
    dangerClass: 'NON_DG',
    shipper: 'PT SEMEN INDONESIA LOGISTIK',
    consignee: 'CV MAJU JAYA MAKASSAR',
    gateInTime: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'L 8842 AB',
    driverName: 'Dedi Kurniawan',
    notes: 'Semen kantong domestik tujuan Pelabuhan Makassar.',
    createdAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
  },
  {
    containerNumber: 'OOLU7381925',
    isoType: '40RF',
    teu: 2,
    status: 'YARD_STACKING',
    category: 'EKSPOR',
    grossWeightKg: 24600,
    tareWeightKg: 4600,
    payloadKg: 20000,
    vgmVerified: true,
    sealNumber: 'OOCL-389102',
    shippingLine: 'OOCL',
    vesselName: 'MV OOCL SHANGHAI',
    voyageNumber: '088E',
    yardLocation: { block: 'C', bay: '06', row: '03', tier: '01' },
    isReefer: true,
    temperatureCelsius: -18.5,
    dangerClass: 'NON_DG',
    shipper: 'PT SEAFOOD PRIMA NUSANTARA',
    consignee: 'TOKYO CENTRAL FISH CO (JAPAN)',
    gateInTime: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'B 9204 TXY',
    driverName: 'Agus Riyadi',
    notes: 'Udang beku ekspor, reefer plug-in aktif monitoring 2 jam sekali.',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    containerNumber: 'CMAU9104823',
    isoType: '40HC',
    teu: 2,
    status: 'CUSTOMS_HOLD',
    category: 'IMPOR',
    grossWeightKg: 30100,
    tareWeightKg: 3950,
    payloadKg: 26150,
    vgmVerified: true,
    sealNumber: 'CMA-881920',
    shippingLine: 'CMA CGM',
    vesselName: 'APL COLUMBUS',
    voyageNumber: '003W',
    yardLocation: { block: 'D', bay: '01', row: '01', tier: '01' },
    isReefer: false,
    temperatureCelsius: null,
    dangerClass: 'CLASS_3_FLAMMABLE',
    shipper: 'BASF CHEMICAL GMBH',
    consignee: 'PT KIMIA FARMA TBK',
    gateInTime: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'B 9011 KLP',
    driverName: 'Hendra Saputra',
    notes: 'Jalur Merah Bea Cukai - pemeriksaan fisik dan dokumen MSDS kimia.',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    containerNumber: 'EGLV5291847',
    isoType: '20GP',
    teu: 1,
    status: 'GATE_IN',
    category: 'EKSPOR',
    grossWeightKg: 19800,
    tareWeightKg: 2250,
    payloadKg: 17550,
    vgmVerified: true,
    sealNumber: 'EMC-481902',
    shippingLine: 'Evergreen Marine',
    vesselName: 'EVER GIVEN',
    voyageNumber: '1092-024',
    yardLocation: { block: 'A', bay: '08', row: '04', tier: '01' },
    isReefer: false,
    temperatureCelsius: null,
    dangerClass: 'NON_DG',
    shipper: 'PT MAYORA INDAH TBK',
    consignee: 'METRO CASH & CARRY (GERMANY)',
    gateInTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'B 9482 FGH',
    driverName: 'Wawan Gunawan',
    notes: 'Biskuit dan kembang gula ekspor kemasan karton.',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    containerNumber: 'SPIL3910482',
    isoType: '20GP',
    teu: 1,
    status: 'YARD_STACKING',
    category: 'DOMESTIK',
    grossWeightKg: 14500,
    tareWeightKg: 2180,
    payloadKg: 12320,
    vgmVerified: true,
    sealNumber: 'SPL-910283',
    shippingLine: 'SPIL (Salam Pacific)',
    vesselName: 'KM ARMADA SEJATI',
    voyageNumber: 'V.044',
    yardLocation: { block: 'B', bay: '05', row: '02', tier: '02' },
    isReefer: false,
    temperatureCelsius: null,
    dangerClass: 'NON_DG',
    shipper: 'PT WINGS SURABAYA',
    consignee: 'TOKO BERKAT BERSAMA MEDAN',
    gateInTime: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'L 9021 UT',
    driverName: 'Surya Prasetyo',
    notes: 'Konsumsi rumah tangga dan deterjen.',
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
  },
  {
    containerNumber: 'TGHU6182940',
    isoType: '20RF',
    teu: 1,
    status: 'YARD_STACKING',
    category: 'IMPOR',
    grossWeightKg: 16400,
    tareWeightKg: 2900,
    payloadKg: 13500,
    vgmVerified: true,
    sealNumber: 'TGH-554129',
    shippingLine: 'ONE (Ocean Network Express)',
    vesselName: 'ONE APUS',
    voyageNumber: '2411E',
    yardLocation: { block: 'C', bay: '02', row: '01', tier: '02' },
    isReefer: true,
    temperatureCelsius: 2.5,
    dangerClass: 'NON_DG',
    shipper: 'AUSTRALIAN BEEF EXPORTERS PTY',
    consignee: 'PT SARI DAGING NUSANTARA',
    gateInTime: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    truckPlateNumber: 'B 9765 QWE',
    driverName: 'Rudi Hartono',
    notes: 'Chilled beef import Australia, chiller +2.5°C.',
    createdAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  }
];
